CXX = g++ -std=c++11 -o


comunes : comunes.cpp
		$(CXX) comunes comunes.cpp

inclusionpares : inclusionpares.cpp
		$(CXX) inclusionpares inclusionpares.cpp

masparesqueimpares : masparesqueimpares.cpp
		$(CXX) masparesqueimpares masparesqueimpares.cpp

num_no_comunes : num_no_comunes.cpp
		$(CXX) num_no_comunes num_no_comunes.cpp

masdelamitadcomunes : masdelamitadcomunes.cpp
		$(CXX) masdelamitadcomunes masdelamitadcomunes.cpp
