<?php
	
	//define("DB_DSN","mysql:host=localhost;port=3306;dbname=test_pw2"); //;port=3306 Mysql y MariaDB 3307
	define("DB_DSN", "mysql:host=betatun.ugr.es;dbname=db80108849_pw2021");
	define("DB_USUARIO", "pw80108849");
	define("DB_PASSWORD", "80108849");
	define("TAMANIO_PAGINA", 3);
	define("URL_BASE","http://localhost:8080/pe2/"); // "http://localhost:8080/pe2/php_PDO_POO/"
	
	define("MIDB","db80108849_pw2021");
	define("TABLA_USUARIOS", "usuarios");	
	define("TABLA_SECCIONES", "secciones");
	define("TABLA_ITEMS", "items");
?>