/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalaki.Monster;

/**
 *
 * @author Josele
 */
public class MonsterView extends javax.swing.JPanel {
    Monster monsterModel;
    /**
     * Creates new form MonsterView
     */
    public MonsterView() {
        initComponents();
    }
    
    private void setMonsterModel(Monster m){
        monsterModel = m;
    }
    
    public void setMonster(Monster m){
        setMonsterModel(m);
        
        jlbName.setText(monsterModel.getName());
        jlbCombatLevel.setText(String.valueOf(monsterModel.getCombatLevel()));
        jlbCombatLevelAgainstCultistPlayer.setText(String.valueOf(monsterModel.getCombatLevelAgainstCultistPlayer()));
        
        badConsequenceView1.setBadC(monsterModel.getBadConsequence());
        prizeView1.setPrize(monsterModel.getPrize());
        
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbEtiqCartaM = new javax.swing.JLabel();
        jlbEtiqNombre = new javax.swing.JLabel();
        jlbEtiqNivelCombate = new javax.swing.JLabel();
        jlbName = new javax.swing.JLabel();
        jlbCombatLevel = new javax.swing.JLabel();
        jlbCombatLevelAgainstCultistPlayer = new javax.swing.JLabel();
        jlbEtiqNivelVSectario = new javax.swing.JLabel();
        badConsequenceView1 = new GUI.BadConsequenceView();
        prizeView1 = new GUI.PrizeView();

        jlbEtiqCartaM.setText("Carta Monstruo");

        jlbEtiqNombre.setText("Nombre:");

        jlbEtiqNivelCombate.setText("Nivel de combate:");

        jlbName.setText("devorador");

        jlbCombatLevel.setText("0");

        jlbCombatLevelAgainstCultistPlayer.setText("0");

        jlbEtiqNivelVSectario.setText("Nivel contra sectario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbEtiqNivelVSectario)
                            .addComponent(jlbEtiqNivelCombate))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbCombatLevel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbCombatLevelAgainstCultistPlayer)
                                .addGap(201, 201, 201)
                                .addComponent(prizeView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jlbName)
                            .addComponent(jlbEtiqCartaM)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbEtiqNombre)
                            .addComponent(badConsequenceView1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbEtiqCartaM)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEtiqNombre)
                    .addComponent(jlbName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEtiqNivelCombate)
                    .addComponent(jlbCombatLevel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbEtiqNivelVSectario)
                            .addComponent(jlbCombatLevelAgainstCultistPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(badConsequenceView1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(prizeView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BadConsequenceView badConsequenceView1;
    private javax.swing.JLabel jlbCombatLevel;
    private javax.swing.JLabel jlbCombatLevelAgainstCultistPlayer;
    private javax.swing.JLabel jlbEtiqCartaM;
    private javax.swing.JLabel jlbEtiqNivelCombate;
    private javax.swing.JLabel jlbEtiqNivelVSectario;
    private javax.swing.JLabel jlbEtiqNombre;
    private javax.swing.JLabel jlbName;
    private GUI.PrizeView prizeView1;
    // End of variables declaration//GEN-END:variables
}
