/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import javax.swing.JOptionPane;
import napakalaki.Napakalaki;
import napakalaki.*;

/**
 *
 * @author joseperoman
 */
public class NapakalakiView extends javax.swing.JFrame {
    Napakalaki napakalakiModel;
    int turnos=0;
    
    public void setNapakalaki(Napakalaki n){
        napakalakiModel=n;
        playerView1.setNapakalaki(n);
        playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
        monsterView1.setMonster(napakalakiModel.getCurrentMonster());
        monsterView1.setVisible(false);
        if(turnos==0){
            jbNextTurn.setEnabled(false);
        }
        jbCombat.setEnabled(false);
        repaint();
    }
    
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jbMeetMonster = new javax.swing.JButton();
        jbCombat = new javax.swing.JButton();
        jbNextTurn = new javax.swing.JButton();
        playerView1 = new GUI.PlayerView();
        monsterView1 = new GUI.MonsterView();
        jlbCombatResult = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbMeetMonster.setText("Conocer monstruo");
        jbMeetMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMeetMonsterActionPerformed(evt);
            }
        });

        jbCombat.setText("COMBATIR!!");
        jbCombat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCombatActionPerformed(evt);
            }
        });

        jbNextTurn.setText("Siguiente turno");
        jbNextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNextTurnActionPerformed(evt);
            }
        });

        jlbCombatResult.setText("Texto De Combate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbNextTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCombat, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbMeetMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbCombatResult))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbCombat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbNextTurn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbMeetMonster)
                        .addGap(39, 39, 39)
                        .addComponent(jlbCombatResult)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(playerView1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMeetMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMeetMonsterActionPerformed
        monsterView1.setVisible(true);
        jbCombat.setEnabled(true);
        
        playerView1.getJbMakeVisible().setEnabled(false);
        

    }//GEN-LAST:event_jbMeetMonsterActionPerformed

    private void jbNextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNextTurnActionPerformed
        if(turnos==0){
            jlbCombatResult.setText("No puedes pasar de turno sin combatir");
        }
        else if (!napakalakiModel.nextTurn())
        {
            jlbCombatResult.setText("No cumples los requisitos para pasar de turno (+ de 4 T ocultos / Pending)");
        }
        else
        {
            playerView1.setPlayer(napakalakiModel.getCurrentPlayer()); 
            monsterView1.setMonster(napakalakiModel.getCurrentMonster());
            monsterView1.setVisible(false);
            jbMeetMonster.setEnabled(true);
           
          
            jlbCombatResult.setText("");
            playerView1.getJbMakeVisible().setEnabled(true);
            jbNextTurn.setEnabled(false);
            
        }
    
    }//GEN-LAST:event_jbNextTurnActionPerformed

    private void jbCombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCombatActionPerformed
        CombatResult combat=napakalakiModel.developCombat();
        if (combat == CombatResult.WIN)
            jlbCombatResult.setText("Has Ganado El Combate");
        else if (combat == CombatResult.LOSE)
            jlbCombatResult.setText("Has perdido el combate, te toca cumplir el mal rollo");
        else if (combat == CombatResult.LOSEANDCONVERT)
            jlbCombatResult.setText("Te has convertido en Cultist");
        else if (combat == CombatResult.WINGAME)
        {
            //jlbCombatResult.setText(
            JOptionPane.showMessageDialog(null,
                    "¡FELICIDADES!\n" +
                    "\nHas derrotado a los monstruos.\n" +
                    "Creditos:\n"+
                    "  Creado Por: Jesús Moyano Doña y Jose Luis Pedraza Román\n"+
                    "\nNapakalakiGame© all rings reserved");
            System.exit(0);
    
        }
        setNapakalaki(napakalakiModel);
        monsterView1.setVisible(true);
        jbCombat.setEnabled(false);
        jbMeetMonster.setEnabled(false);
        jbNextTurn.setEnabled(true);
        turnos++;
        setNapakalaki(napakalakiModel);
        
        //variable para controlar el nextturn
        
    }//GEN-LAST:event_jbCombatActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showView() {
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JButton jbCombat;
    private javax.swing.JButton jbMeetMonster;
    private javax.swing.JButton jbNextTurn;
    private javax.swing.JLabel jlbCombatResult;
    private GUI.MonsterView monsterView1;
    private GUI.PlayerView playerView1;
    // End of variables declaration//GEN-END:variables
}
