/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalaki.Prize;

/**
 *
 * @author Josele
 */
public class PrizeView extends javax.swing.JPanel {
    
    Prize prizeModel;
    /**
     * Creates new form PrizeView
     */
    public PrizeView() {
        initComponents();
    }

    private void setPrizeModel(Prize p){
        prizeModel = p;
    }
    
    public void setPrize(Prize p){
        setPrizeModel(p);
        
        jlbNTreasures.setText(String.valueOf(prizeModel.getTreasures()));
        jlbLevel.setText(String.valueOf(prizeModel.getLevel()));
        // la siguiente instrucción hace que los cambios en la vista sean efectivos
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbEtiqBuenRollo = new javax.swing.JLabel();
        jlbEtiqNTesoros = new javax.swing.JLabel();
        jlbEtiqNivel = new javax.swing.JLabel();
        jlbNTreasures = new javax.swing.JLabel();
        jlbLevel = new javax.swing.JLabel();

        jlbEtiqBuenRollo.setText("BUEN ROLLO");

        jlbEtiqNTesoros.setText("Numero de tesoros:");

        jlbEtiqNivel.setText("Nivel:");

        jlbNTreasures.setText("3");

        jlbLevel.setText("4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbEtiqNTesoros)
                            .addComponent(jlbEtiqNivel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbNTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlbEtiqBuenRollo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbEtiqBuenRollo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEtiqNTesoros)
                    .addComponent(jlbNTreasures))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEtiqNivel)
                    .addComponent(jlbLevel))
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbEtiqBuenRollo;
    private javax.swing.JLabel jlbEtiqNTesoros;
    private javax.swing.JLabel jlbEtiqNivel;
    private javax.swing.JLabel jlbLevel;
    private javax.swing.JLabel jlbNTreasures;
    // End of variables declaration//GEN-END:variables
}
