/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
 
/**
 *
 * @author joseperoman
 */
import java.awt.Color;
import napakalaki.Treasure;
public class TreasureView extends javax.swing.JPanel {

    Treasure treasureModel;
    boolean selected = false;
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }
    
    /*
    public void setTreasure (Treasure aTreasure) {
        // se actualiza el atributo de referencia
        treasureModel = aTreasure;
        // se actualiza la vista del tesoro, por ejemplo
        this.name.setText (treasureModel.getName());
        // la siguiente instrucción hace que los cambios en la vista sean efectivos
        repaint();
    }
    */
    private void setTreasureModel(Treasure t){
        treasureModel = t;
    }
    
    public void setTreasure(Treasure t){
        setTreasureModel(t);
        
        jlbNameTreasure2.setText(treasureModel.getName());
        jlbBonusTreasure2.setText(String.valueOf(treasureModel.getBonus()));
        jlbTypeTreasure2.setText(String.valueOf(treasureModel.getType()));
         // la siguiente instrucción hace que los cambios en la vista sean efectivos
        repaint();
    }
    
    public boolean isSelected(){
        return selected;
    }
    
    public Treasure getTreasure(){
        return treasureModel;
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbNameTreasure = new javax.swing.JLabel();
        jlbBonus = new javax.swing.JLabel();
        jlbType = new javax.swing.JLabel();
        jlbEtiqCartaTesoro = new javax.swing.JLabel();
        jlbNameTreasure2 = new javax.swing.JLabel();
        jlbBonusTreasure2 = new javax.swing.JLabel();
        jlbTypeTreasure2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 200, 200)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jlbNameTreasure.setText("Nombre");

        jlbBonus.setText("Bonus");

        jlbType.setText("Tipo de tesoro");

        jlbEtiqCartaTesoro.setText("CARTA TESORO");

        jlbNameTreasure2.setText("jLabel1");

        jlbBonusTreasure2.setText("jLabel2");

        jlbTypeTreasure2.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlbNameTreasure)
                                .addComponent(jlbBonus))
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlbNameTreasure2)
                                .addComponent(jlbBonusTreasure2)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jlbType)
                            .addGap(18, 18, 18)
                            .addComponent(jlbTypeTreasure2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jlbEtiqCartaTesoro)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbEtiqCartaTesoro)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNameTreasure)
                    .addComponent(jlbNameTreasure2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbBonus)
                    .addComponent(jlbBonusTreasure2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTypeTreasure2)
                    .addComponent(jlbType))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

        if(this.isSelected()){ 
            selected=false;
            this.setBackground(Color.red);
            this.setOpaque(selected);
            repaint();
        }
        else{
            selected=true; 
            this.setBackground(Color.green);
            this.setOpaque(selected);
            repaint();    
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbBonus;
    private javax.swing.JLabel jlbBonusTreasure2;
    private javax.swing.JLabel jlbEtiqCartaTesoro;
    private javax.swing.JLabel jlbNameTreasure;
    private javax.swing.JLabel jlbNameTreasure2;
    private javax.swing.JLabel jlbType;
    private javax.swing.JLabel jlbTypeTreasure2;
    // End of variables declaration//GEN-END:variables
}
